apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecommerce-dss
spec:
  replicas: 1
  selector: {matchLabels: {app: backend}}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend:latest
        ports: [{containerPort: 8000}]
