global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ecommerce-dss-monitor'

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  # Backend API health check
  - job_name: 'backend-health'
    static_configs:
      - targets: ['ecommerce-dss-project-backend-1:8000']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http
    honor_labels: true
    honor_timestamps: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: ${1}

  # Kafka JMX metrics (disable until JMX exporter is configured)
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka:9997']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # MongoDB Exporter
  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Airflow metrics (disable until metrics endpoint is configured)
  - job_name: 'airflow-webserver'
    static_configs:
      - targets: ['airflow-webserver:8080']
    metrics_path: /admin/metrics
    scrape_interval: 30s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    scrape_interval: 30s

  # Kafka UI metrics (if available)
  - job_name: 'kafka-ui'
    static_configs:
      - targets: ['kafka-ui:8080']
    metrics_path: /actuator/prometheus
    scrape_interval: 30s
    scrape_timeout: 10s

  # Application container metrics (disable until metrics endpoints are added)
  - job_name: 'container-metrics'
    static_configs:
      - targets: ['backend:8000', 'kafka:9092', 'spark-master:8080']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
  # Spark master metrics
  
  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http
    honor_timestamps: true
    params:
      format: ['prometheus']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^spark_.*'
        action: keep

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
